# GitHub Sponsors funding configuration
# This file defines the funding options displayed in the repository's "Sponsor" button

# Primary funding platform
buy_me_a_coffee: raphaelsqu7

# Additional funding platforms (currently not configured)
# Uncomment and add your usernames when you set up additional platforms
# github: # GitHub Sponsors username(s) - supports up to 4 usernames
# patreon: # Patreon username
# open_collective: # Open Collective username
# ko_fi: # Ko-fi username
# tidelift: # Format: platform-name/package-name (e.g., npm/babel)
# community_bridge: # Community Bridge project name
# liberapay: # Liberapay username
# issuehunt: # IssueHunt username
# lfx_crowdfunding: # LFX Crowdfunding project name
# polar: # Polar username
# custom: # Custom sponsorship URLs - supports up to 4 URLs
#   - https://example.com/sponsor1
#   - https://example.com/sponsor2